### ISSUE TITLE
PIL/Pillow module error

### ISSUE THREAD

**Issue by WWWFWWW** [grst/geos#16]
```
Traceback (most recent call last):
  File "/Users/<user>/Library/Python/3.7/bin/geos", line 6, in <module>
    from geos.scripts.runserver import run_app
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/geos/__init__.py", line 4, in <module>
    import geos.server
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/geos/server.py", line 3, in <module>
    from geos.print import print_map
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/geos/print.py", line 8, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'
```

Although it might have been be included with Anaconda, with normal Python 3.7 installation, there is an additional step to install PIL or pillow module for geos to work on Mac OS. You might add that to the installation docs...
`pip3 install pillow` works nicely.

**Comment by grst** [comment]
Hi,
thanks for reporting.

I am travelling until end of May and take care of this when I am back.
Let's keep the issue open until then...

Cheers,
Gregor
